config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/partenaires', to: 'home#partenaires'
  get '/journal', to: 'home#journal'
  get '/equipe', to: 'home#equipe'
  get '/partenaires', to: 'home#partenaires'
  get '/veuveinfidele', to: 'home#veuveinfidele'
  get '/fanfaredamour', to: 'home#fanfaredamour'
  get '/projets', to: 'home#projets'
  get '/prochainesdates', to: 'home#prochainesdates'


root 'home#index' 


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    
    def index
      # Votre code ici
    end
    
    def journal
      # Code pour rendre la page des partenaires
    end

    def equipe
      # Code pour rendre la page des partenaires
    end

    def partenaires
      # Code pour rendre la page des partenaires
    end

    def veuveinfidele
      # Code pour rendre la page des partenaires
    end

    def fanfaredamour
      # Code pour rendre la page des partenaires
    end

    def projets
      # Code pour rendre la page des partenaires
    end



  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<%= link_to "Accueil", root_path, class: "nav-link" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <%= link_to "Journal", journal_path, class: "nav-link" %>

    </li>

    <li class="nav-item active">
    <%= link_to "equipe", equipe_path, class: "nav-link" %>
    </li>

 

    <li class="nav-item">
      <%= link_to "Partenaires", partenaires_path, class: "nav-link" %>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
       Spectacles
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "La Veuve infidèle", veuveinfidele_path, class: "nav-link" %>
        <%= link_to "Fanfare d'Amour", fanfaredamour_path, class: "nav-link" %>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="projets.html
        ">Idées vagues</a>
      </div>
   
  </ul>
 
</div>
</nav>

<div class="jumbotron">
        

<h1 class="display-4">Namasté !</h1>
<h1> Les laboratoires du bazar baroque</h1>
<hr class="my-4">
<p></p>
<p class="lead">
  <a class="btn btn-primary btn-lg" href="prochainesdates.html" role="button">Prochaines dates</a>
</p>
  
</div>

app/views/home/equipe.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">

    <title>Les comédiens</title>



  <body>




<div class="mycontainer">





<h2> Comédiennes et comédiens des Laboratoire du Bazar Baroque</h2>



<br/>
<br/>

<div class="row">

  <div class="col-sm-6">
      <div class="card">
            <div class="card-body">
               <img src= assets/ElodieDevin-Photo.jpg alt="Photo de la comédienne Elodie Devin" >
               <h5 class="card-title">Elodie Devin</h5>
               <p class="card-text">Depuis toute jeune, Elodie manifeste un élan naturel pour le jeu, la comédie et la danse qu’elle exprime en suivant les cours de théâtre du collège et lors de concours d’éloquence au lycée. Elle suit d’abord des cours amateurs au « Circulo Teatral » de Mexico, étant expatriée, puis à son retour à Paris, elle se professionnalise aux cours Florent. Menant en parallèle une carrière commerciale, elle vit le théâtre comme une passion à travers des ateliers et cours amateurs : « Ateliers pour l’instant » de Julie Goudard, cours d’improvisation à l’EFIT de Esteban Perroy et dernièrement les cours de Maxime Bailleul aux Ateliers du Sudden. Au théâtre, elle a interprété les rôles de Clarisse dans "Mais N'te promène donc pas toute nue" de Feydeau, Francine dans "Dormez, Je le veux ! de Feydeau", Elmire dans "Le Tartuffe ou l'Imposteur" de Molière, mises en scène de Christian-David Meslé, Olivia dans « La Nuit des Rois » de W. Shakespeare mise en scène par Julie Goudard; Juliette, Harpagon et Rosine dans « Le Théâtre s’invite à l’Opéra mis en scène par Marco Avallone.</p>
               <a href="https://www.facebook.com/elodie.devin.7" class="btn btn-primary">Plus d'infos</a>
            </div>
      </div>
  </div>



  <div class="col-sm-6">
      <div class="card">
            <div class="card-body">
                <img src= assets/AymericDein-Photo.jpg alt="Photo du comédien Aymeric Dein" >
                <h5 class="card-title">Aymeric Dein</h5>
                <p class="card-text">Aymeric Dein,alias Frère Laurent, découvre le théâtre assez tardivement lors de ses études universitaires en Bretagne, à Rennes 2. Pourtant, il choisira la voie du cinéma pour devenir technicien. Malgré des études à l'Esra et avoir travaillé plusieurs années pour la télévision et le cinéma, Aymeric reste passionnée de théâtre. Continuant toujours à faire quelques rôles dans les courts métrages, il change de carrière en 2014 et intègre les Ateliers du Sudden puis Claude Mathieu en 2016 pour apprendre le métier de comédien. En 2021, il joue Oronte et Dubois dans une adaptation du Misanthrope. Il apparaît aussi dans la série 3615 Monique. Actuellement, il prépare aussi l'adaptation de Georges Dandin au théâtre du Nord-Ouest. .</p>
                <a href="https://nawak.com/book/aymeric_dein" class="btn btn-primary">Plus d'infos</a>
            </div>
       </div>
    </div>
    

  </div>




  

    <div class="row">

      <div class="col-sm-6">
          <div class="card">
                <div class="card-body">

                                    <img src= assets/StephanBecquerel-Photo.jpg alt="Photo du comédien Stephan Becquerel">
                      <h5 class="card-title">Stéphan Becquerel</h5>
                    <p class="card-text">Etudiant en 3eme année d'histoire de l'art,
                    et passionnée de théâtre depuis l'âge de 7 ans. elle a été élève au
                    conservatoire de théâtre d'Orléans pendant 3 ans. Arrivée à Paris pour
                      ses études, elle a été membre de la compagnie Candela dans le  6eme
                      arrondissement pendant un an.
                      Depuis septembre 2021, élève au conservatoire de théâtre du centre.
                      </p>
                    <a href="https://demainleprintemps.fr/" class="btn btn-primary">Plus d'infos</a>
                </div>
          </div>
      </div>


      <div class="col-sm-6">
      <div class="card">
            <div class="card-body">
            <img src= assets/JosephinedeCastelbajac-Photo.jpg alt="Photo de la comédienne Joséphine de Casltelbajac">
              <h5 class="card-title">joséphine de Castelbajac</h5>
              <p class="card-text"> Etudiante en 3eme année d'histoire de l'art,
              et passionnée de théâtre depuis l'âge de 7 ans. elle a été élève au
              conservatoire de théâtre d'Orléans pendant 3 ans. Arrivée à Paris pour
              ses études, elle a été membre de la compagnie Candela dans le  6eme
              arrondissement pendant un an.
              Depuis septembre 2021, élève au conservatoire de théâtre du centre.</p>
              <a href="https://conservatoires.paris.fr/p/3328-admissions-en-art-dramatique" class="btn btn-primary">Plus d'infos</a>
            </div>
      </div>
      
    </div>


    <div class="col-sm-6">
      <div class="card">
            <div class="card-body">
            <img src= assets/Facteur-Boyaire-Photo.jpg alt="Photo de la comédienne Joséphine de Casltelbajac">
              <h5 class="card-title">Le facteur Boyaire</h5>
              <p class="card-text"> L'auteur, avec Labiche, de la pièce. Egalement metteur en scène, régisseur, chargé de diffusion, masseur; etc.</p>
              <a href="https://boyaire.wixsite.com/acteur" class="btn btn-primary">Plus d'infos</a>
            </div>
      </div>

    

</div>

 
  </body>
</html>

app/views/home/fanfaredamour.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">

    <title>Partenariats</title>


 


  <body>

  




<div class="mycontainer">


  <h1></h1>



  
  
  <div class="myimg">
  

    <div class ="center">

      <div class ="parag01">
            <h4>Ouvrez vos mirettes, c'est à Marseille que ça se passe !"</h4>
            <img src= assets/Marylin_Marseille.jpg id="affiche">
        <br/>
        <br/>
            <p >          
            On reprend à Marseille la fameuse pièce du facteur Boyaire, adaptée du célèbre film "Certains l'aiment chaud" (1959) de l'immense billy Wilder (avec Marylin Monroe en vedette), remake hollywodien d'un film allemand de 1951 ("Fanfaren der Liebe" de Kurt hoffmann) lui-même largement copié sur l'original français réalisé par Richard Pottier et sorti en 1935: "Fanfare d'amour" (on s'arrête là). Eh bien, de nos jours, c'est la compagnie Root'Arts qui s'y colle ! Renseignez-vous auprès d'eux pour les prochaines dates.
          </p>
            <a class="nav-link" href="https://cie-rootarts.fr/spectacles/">Compagnie Root'Arts</a>
       </div>

  <br/>

   
  


        <div class ="parag01">

          <h4>La cie Root' Art reprend "Fanfare d'Amour : vaudeville épique"</h4>
          <img src= assets/farootarts.jpg id="affiche">
          <br/>
          <br/>
          <p >  L'histoire de deux comédiens, deux tocards, qui se disputent dans un bar au sujet d'un projet de théâtre complètement fou : l'adaptation à la scène du célèbre film de Billy Wilder "Certains l'aiment chaud". Au moment de partir, ils réalisent que ni l'un ni l'autre n'a les moyens de payer l'addition. Contraints et forcés, ils vont alors tenter de jouer au chapeau devant les clients du bar le fameux texte. Entreprise périlleuse qui les mènera au delà de ce qu'ils imaginaient, quelque part entre fiction et réalité, entre le monde des hommes et celui des femmes.
          </p>

        </div>
    
       
      
        <div class ="parag01">

                    <p >
            Les deux comédiens de Root'Arts suivent les pas de leurs grandes devancières: Jayne Mansfield et Mamie Van Doren, clones de Marylin Monroe lancées par les studios afin de concurrencer la star qui avait osé défié leur loi (en déménageant à New-York pour produire elle-même ses films, en 1962). Les clones copièrent tout de Marylin: sa blondeur, ses mensurations, sa poitrine... et son fameux déhanché (cf la légende du talon légèrement limé). Deux des "3 M"  (Mayrlin Monroe et Jayne Mansfield) connurent une fin tragique. 

            On souhaite à David et rodolphe la longévité de la survivante, qui continue à 95 ans, en tant que "Blonde Bombshell Mamie van Doren", à perpétuer sur Facebook le mythe de la blonde des années 50. 
                    </p>

            <img src= assets/ThreeM.jpg id="Les 3 M dans les années 60">


        </div>

<br/>

<iframe width="560" height="315" src="https://www.youtube.com/embed/XVx4GBx4cb0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

<br/>

<a class="nav-link" href="https://www.facebook.com/profile.php?id=100032868326359">Blonde Bombshell Mamie Van Doren (95 ans) toujours dans le coup sur FaceBook!</a>
<img src= assets/MamieVanDoren.jpg id="affiche">

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">

    <title>Les laboratoires du Bazar Baroque</title>

  <body>
  
 

<div class="mycontainer">

<div class ="center">
 
      <div class="myimg">
        
      <img src= assets/Vi-Affiche.jpg id="affiche">

      </div>


 </div>

 

</div>

app/views/home/journal.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">

    <title>Le précieux journal des laboratoires du Bazar Baroque</title>
 


  <body>


<div class="mycontainer">



  
      <div class ="center">
      

        <div class ="articljour">
         
          <h4> On espère relancer le podcast</h4>
          <p class="articldate"> Le 29 avril de l'an 2023</p>
          
          <img src= assets/Theatrophone03.jpg id="affiche">
          <p> Le cataclysme qui a emporté notre précédent site internet -et contre lequel notre astrologue à Bénarès a malheureusment négligé de nous avertir- a laissé un grand vide : la grande opération de podcasts sonores avec l'Inde pour sujet est reportée. On espère s'en remettre et vous proposer le plus rapidement possible ces enregistrements de textes de voyageurs aux Indes, L'inde des minarets (le nord) ainsi que l'Inde des palmes (le sud). Les auteurs de ces textes choisis sont,
           entre autres, Emile Guimet -fondateur du musée du même nom- et surtout Alexandra David-Néel, la grand exploratrice -surtout connue pour ses voyages au Tibet mais qui a aussi traversé l'inde, bien sûr.  </p>
          
    

        </div>



        <div class ="articljour">
         
          <h4> Notre astrologue nous indique les meilleures dates</h4>
          <p class="articldate"> Le 6 janvier de l'an 2023</p>

          <img src= assets/14-Janvier-AstroIndienne-00.jpg id="affiche">

          <p>   Notre astrologue à Bénares nous a signalé qu'à la date du 14 janvier 2023 Vénus entre en Bélier: La planète de l’amour s’apprête à quitter la constellation des Poissons pour celle du Bélier : et croyez-nous, l’ambiance astrale n’est pas la même ! Ca va chauffer sur le plateau dans les questions amoureuses ! Alors venez nombreux pour cette nouvelle date de représentation extraordinaire soigneusement sélectionnée dans les étoiles par notre astrologue à Bénarès!</p>
          <p>    Alors venez nombreux pour cette nouvelle date de représentation extraordinaire soigneusement sélectionnée dans les étoiles par notre astrologue à Bénarès!</p>
    

        </div>


          

     </div>  






      
 

</div>






 
  </body>
</html>

app/views/home/partenaires.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">

    <title>Partenariats</title>


 


  <body>

  




<div class="mycontainer">


  <h1></h1>



  
  
  <div class="myimg">
  

    <div class ="center">

      <div class ="parag01">
            <h4>Ouvrez vos mirettes, c'est à Marseille que ça se passe !"</h4>
            <img src= assets/Marylin_Marseille.jpg id="affiche">
        <br/>
        <br/>
            <p >          
            On reprend à Marseille la fameuse pièce du facteur Boyaire, adaptée du célèbre film "Certains l'aiment chaud" (1959) de l'immense billy Wilder (avec Marylin Monroe en vedette), remake hollywodien d'un film allemand de 1951 ("Fanfaren der Liebe" de Kurt hoffmann) lui-même largement copié sur l'original français réalisé par Richard Pottier et sorti en 1935: "Fanfare d'amour" (on s'arrête là). Eh bien, de nos jours, c'est la compagnie Root'Arts qui s'y colle ! Renseignez-vous auprès d'eux pour les prochaines dates.
          </p>
            <a class="nav-link" href="https://cie-rootarts.fr/spectacles/">Compagnie Root'Arts</a>
       </div>

  <br/>

   
  


        <div class ="parag01">

          <h4>La cie Root' Art reprend "Fanfare d'Amour : vaudeville épique"</h4>
          <img src= assets/farootarts.jpg id="affiche">
          <br/>
          <br/>
          <p >  L'histoire de deux comédiens, deux tocards, qui se disputent dans un bar au sujet d'un projet de théâtre complètement fou : l'adaptation à la scène du célèbre film de Billy Wilder "Certains l'aiment chaud". Au moment de partir, ils réalisent que ni l'un ni l'autre n'a les moyens de payer l'addition. Contraints et forcés, ils vont alors tenter de jouer au chapeau devant les clients du bar le fameux texte. Entreprise périlleuse qui les mènera au delà de ce qu'ils imaginaient, quelque part entre fiction et réalité, entre le monde des hommes et celui des femmes.
          </p>

        </div>
    
       
      
        <div class ="parag01">

                    <p >
            Les deux comédiens de Root'Arts suivent les pas de leurs grandes devancières: Jayne Mansfield et Mamie Van Doren, clones de Marylin Monroe lancées par les studios afin de concurrencer la star qui avait osé défié leur loi (en déménageant à New-York pour produire elle-même ses films, en 1962). Les clones copièrent tout de Marylin: sa blondeur, ses mensurations, sa poitrine... et son fameux déhanché (cf la légende du talon légèrement limé). Deux des "3 M"  (Mayrlin Monroe et Jayne Mansfield) connurent une fin tragique. 

            On souhaite à David et rodolphe la longévité de la survivante, qui continue à 95 ans, en tant que "Blonde Bombshell Mamie van Doren", à perpétuer sur Facebook le mythe de la blonde des années 50. 
                    </p>

            <img src= assets/ThreeM.jpg id="Les 3 M dans les années 60">


        </div>

<br/>

<iframe width="800" height="615" src="https://www.youtube.com/embed/XVx4GBx4cb0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

<br/>

<a class="nav-link" href="https://www.facebook.com/profile.php?id=100032868326359">Blonde Bombshell Mamie Van Doren (95 ans) toujours dans le coup sur FaceBook!</a>

<img src="assets/MamieVanDoren.jpg" id="affiche" style="max-width: 800px;">





    
        









</div>






 
  </body>
</html>

app/views/home/prochainesdates.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">

    <title>Prochaines dates</title>


<div class="mycontainer">

</br>
</br>
</br>
</br>

<p>
Pas de dates prévues dans votre ville actuellement.
  </p>
  <p>
    Cependant : deux dates sont à l'étude aux beaux jours de l'an 2023 dans des communes proches de Paris : les bienheureuse Villejuif et Maisons-Alfort.
    </p>

    <p>
     Une autre date est également à l'étude pur Créteil, fin juin 2023, au Théâtre Casalis.
      </p> 
  <p>
  Merci de votre précieuse patience.
  </p>


  </div>



 
  </body>
</html>

app/views/home/veuveinfidele.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">

    <title>La veuve infidèle</title>

 




    </head>

  <body>





<div class="mycontainer">


         <h1></h1>


     
          <p>
        
          </p>
          
          <div class ="center">
            <div class ="parag01">
    
              <h4>"La Veuve infidèle", d'à peu près Eugène Labiche</h4>
          
              <a class="nav-link" href=" https://www.billetreduc.com/296101/evtcrit.htm">Les avis des spectateurs<span class="sr-only">(current)</span></a>

         
           
    
            
            <h5> Une comédie romantique à la sauce Bollywood</h5>
    
                      <p >
                        Dans l'Inde fabuleuse, à Pondichéry, une belle marquise vient d'hériter de l'immense fortune de son défunt mari. C'est l'ébullition dans la colonie. Qui mettra la main sur ces beautés terrestres ?...

                        Pour ravir la veuve et les bijoux, les adorateurs de Kali rôdent la nuit tandis que les beaux esprits font assaut de galanterie ; esprits fiévreux, résolus aux plus fantasques tentatives: se faire voleur au bal des Fakirs, implorer une réincarnation parmi les vivants, etc.
                        
                        Une comédie à la sauce Bollywood, dans la veine orientaliste du 19ème siècle, très librement inspir-expirée de la plus exotique des pièces d'Eugène Labiche.
                        
                        Avertissement: comédie ultra-romantique !
                        
                        Dans les vieilles légendes sanskrites il est question de destinées amoureuses, des relations karmiques liant deux âmes appelées à se rencontrer. Quand, dans la ronde des réincarnations, cette convergence survient, les deux âmes se reconnaissent instantanément...

                      </p>
    
            </div>
          </div>  
    
          <div class="myimg">
          
            <img src= assets/Vi-Affiche.jpg id="affiche">

          </div>

</div>






 
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appsqlite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<link rel="stylesheet" type="text/css" href="/assets/custom.css">


  </head>

  <body>
  <%= render partial: 'navbar' %>

    <%= yield %>
  </body>
</html>